spring.application.name=demembeddingservice
spring.datasource.url=jdbc:h2:mem:frodo;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

ollama.base-url=http://localhost:11434
ollama.model=nomic-embed-text